# Generated by Django 5.0.3 on 2024-03-28 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResturantMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=264)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResturantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=264, null=True)),
                ('price', models.CharField(blank=True, choices=[('$', '1'), ('$$', '2'), ('$$$', '3'), ('$$$$', '4'), ('$$$$$', '5')], max_length=5, null=True)),
                ('description', models.TextField(blank=True, max_length=264, null=True)),
                ('phone_no', models.IntegerField(blank=True, null=True)),
                ('restaurant_photo', models.ImageField(blank=True, default='', null=True, upload_to='restaurant_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='ResturantMenuPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_photo', models.ImageField(blank=True, default='', null=True, upload_to='dish_photo/')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.resturantmenu')),
            ],
        ),
        migrations.AddField(
            model_name='resturantmenu',
            name='resturant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.resturantmodel'),
        ),
        migrations.CreateModel(
            name='ResturantCuisineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=20)),
                ('resturant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.resturantmodel')),
            ],
        ),
    ]
